FROM node:20-alpine AS build
WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

FROM nginx:alpine
WORKDIR /usr/share/nginx/html

# 复制构建产物到 Nginx 的目录
COPY --from=build /app/dist .

# 可选：复制自定义的 Nginx 配置
# COPY nginx.conf /etc/nginx/nginx.conf

# 暴露 Nginx 端口
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]